from __future__ import annotations

from pathlib import Path
import hashlib
import shutil
import zipfile


REQUIRED_MEMBERS = {
    "designmap.xml",
    "META-INF/container.xml",
}


class IDMLPackageError(ValueError):
    """Raised when an IDML package is missing, corrupt, or structurally invalid."""


class IDMLPackage:
    """Validate, inspect, and extract an IDML ZIP package."""

    def __init__(self, idml_path: Path, extraction_root: Path) -> None:
        self.idml_path = Path(idml_path).resolve()
        self.extraction_root = Path(extraction_root).resolve()
        self.root: Path | None = None
        self.members: tuple[str, ...] = ()

    def validate(self) -> tuple[str, ...]:
        if not self.idml_path.exists():
            raise FileNotFoundError(self.idml_path)
        if self.idml_path.suffix.lower() != ".idml":
            raise IDMLPackageError(f"Expected .idml package: {self.idml_path}")
        if not zipfile.is_zipfile(self.idml_path):
            raise IDMLPackageError(f"IDML is not a valid ZIP package: {self.idml_path}")

        try:
            with zipfile.ZipFile(self.idml_path, "r") as package:
                names = tuple(name.replace("\\", "/") for name in package.namelist())
                self.members = names
                normalized = {name.lstrip("/") for name in names}
                missing = REQUIRED_MEMBERS - normalized
                if missing:
                    raise IDMLPackageError(
                        f"IDML package is missing required members: {sorted(missing)}"
                    )
                bad_member = package.testzip()
                if bad_member is not None:
                    raise IDMLPackageError(
                        f"IDML package contains a corrupt ZIP member: {bad_member}"
                    )
        except zipfile.BadZipFile as exc:
            raise IDMLPackageError(f"Invalid IDML ZIP: {exc}") from exc
        return self.members

    def extract(self) -> Path:
        self.validate()
        target = self.extraction_root / self.idml_path.stem
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True, exist_ok=True)

        with zipfile.ZipFile(self.idml_path, "r") as package:
            for member in package.infolist():
                # IDML is normally generated by InDesign and should not contain
                # traversal paths. Still reject them so extraction is safe for
                # externally supplied packages.
                relative = Path(member.filename.replace("\\", "/"))
                if relative.is_absolute() or ".." in relative.parts:
                    raise IDMLPackageError(
                        f"Unsafe path in IDML package: {member.filename}"
                    )
                package.extract(member, target)

        self.root = target
        self._validate_extracted_files()
        return target

    def resolve(self, relative_path: str) -> Path:
        if self.root is None:
            raise RuntimeError("IDML package has not been extracted")
        relative = Path(relative_path.replace("\\", "/"))
        if relative.is_absolute() or ".." in relative.parts:
            raise IDMLPackageError(f"Unsafe relative IDML path: {relative_path}")
        return self.root / relative

    def image_files(self) -> list[Path]:
        if self.root is None:
            raise RuntimeError("IDML package has not been extracted")
        extensions = {".jpg", ".jpeg", ".png", ".gif", ".tif", ".tiff", ".bmp", ".eps", ".pdf"}
        return sorted(p for p in self.root.rglob("*") if p.is_file() and p.suffix.lower() in extensions)

    def sha256(self) -> str:
        digest = hashlib.sha256()
        with self.idml_path.open("rb") as stream:
            for block in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(block)
        return digest.hexdigest()

    def _validate_extracted_files(self) -> None:
        assert self.root is not None
        for required in REQUIRED_MEMBERS:
            if not (self.root / required).is_file():
                raise IDMLPackageError(
                    f"Required IDML member was not extracted: {required}"
                )
